
export const foodCategories = [
  { id: "privateDinners", label: "Private Dinners", emoji: "🍽️" },
  { id: "cookingClasses", label: "Cooking Classes", emoji: "👨‍🍳" },
  { id: "wineTastings", label: "Wine Tastings", emoji: "🍷" },
  { id: "popupRestaurants", label: "Pop-up Restaurants", emoji: "🏪" },
  { id: "foodTours", label: "Food Tours", emoji: "🚶‍♂️" },
  { id: "mixologyCocktails", label: "Mixology/Cocktails", emoji: "🍸" },
  { id: "artisanMarkets", label: "Artisan Markets", emoji: "🏪" },
  { id: "farmToTable", label: "Farm-to-Table", emoji: "🌱" },
  { id: "streetFood", label: "Street Food", emoji: "🌮" },
  { id: "bakingWorkshops", label: "Baking Workshops", emoji: "🥐" },
  { id: "fermentation", label: "Fermentation", emoji: "🫙" },
  { id: "teaCeremonies", label: "Tea Ceremonies", emoji: "🍵" },
  { id: "cheeseTastings", label: "Cheese Tastings", emoji: "🧀" },
  { id: "coffeeExperiences", label: "Coffee Experiences", emoji: "☕" },
  { id: "beerTastings", label: "Beer Tastings", emoji: "🍺" },
  { id: "chocolateWorkshops", label: "Chocolate Workshops", emoji: "🍫" },
  { id: "spiritsWhiskey", label: "Spirits & Whiskey", emoji: "🥃" },
  { id: "oliveOilTastings", label: "Olive Oil Tastings", emoji: "🫒" },
  { id: "honeyBeekeeping", label: "Honey & Beekeeping", emoji: "🍯" },
  { id: "breadMaking", label: "Bread Making", emoji: "🍞" },
];

export const dietaryRestrictions = [
  { id: "vegan", label: "Vegan", emoji: "🌱" },
  { id: "vegetarian", label: "Vegetarian", emoji: "🥗" },
  { id: "glutenFree", label: "Gluten-free", emoji: "🌾" },
  { id: "dairyFree", label: "Dairy-free", emoji: "🥛" },
  { id: "nutAllergies", label: "Nut allergies", emoji: "🥜" },
  { id: "kosher", label: "Kosher", emoji: "✡️" },
  { id: "halal", label: "Halal", emoji: "☪️" },
  { id: "keto", label: "Keto", emoji: "🥩" },
  { id: "paleo", label: "Paleo", emoji: "🦴" },
  { id: "lowSodium", label: "Low-sodium", emoji: "🧂" },
  { id: "sugarFree", label: "Sugar-free", emoji: "🍬" },
  { id: "shellfishAllergy", label: "Shellfish allergy", emoji: "🦐" },
  { id: "soyFree", label: "Soy-free", emoji: "🫘" },
  { id: "eggFree", label: "Egg-free", emoji: "🥚" },
  { id: "lactoseIntolerant", label: "Lactose intolerant", emoji: "🥛" },
];
