// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsianzkmvbbaahoeivnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzaWFuemttdmJiYWFob2Vpdm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTg2MDYsImV4cCI6MjA2MzU3NDYwNn0.wWx7pSYfUJTIMuSvBluxPDgqU8SuKuGI4TQTUOEAKh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);